config/routes.rb
Rails.application.routes.draw do
  # Pour les Login/logout des Users
  devise_for :users
  # devise_scope :user do
  #   get'CHECK later pour Login/logout'
  # end

  # Page d'accueil ?
  root to: "pages#home"

  # Users :
  resources :users, only: [:show, :edit, :update]
  # actionsItems
  resources :items do
    resources :bookings, only: [:create]
  end

  # Bookings
  resources :bookings, only: [:index, :show, :update, :create] do
    patch 'reviews', to: 'reviews#update'
  end

  get "my_items", to: "items#my_items"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
# Associations
  belongs_to :item
  belongs_to :user

# Validations


  validates :start_at, :end_at, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  # Associations
  has_many :bookings
  belongs_to :user

  # Validations

  validates :name, presence: true, uniqueness: true
  UNIVERS = ["Star Wars", "Le Seigneurs Des Anneaux", "Harry Potter", "Indiana Jones", "Men in Black", "Forrest Gump", "Doctor Who", "Shinnig", "5ème élément", "autres"]
  validates :univers, inclusion: { in: UNIVERS }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Associations
  has_many :bookings
  has_many :items

  # Validations
  validates :email, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:index]
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = current_user.bookings
  end

  def create
    @item = Item.find(params[:item_id])
    dates = booking_params[:start_at].split(" to ")
    @booking = Booking.new(start_at: dates.first, end_at: dates.last, status: "En attente")
    @booking.item = @item
    @booking.user = current_user
    if @booking.save
      redirect_to bookings_path()
    else
      render :new
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      redirect_to booking_path(@booking)
    else
      render :edit
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_at, :item_id, :user_id)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
    # @items = Item.includes(:user)  # ici
  end

  def new
    @item = Item.new
  end

  def create

    @item = Item.new(item_params)
    @item.user = current_user
    if @item.save!

      redirect_to items_path
    else
      render :new, status: :unprocessable_entity

    end
  end

  def show
    @booking = Booking.new
    @item = Item.find(params[:id])

    if @item.user_id == current_user
      @item.user_id = true
    end
    if @item.geocoded?
      @markers = [{ lat: @item.latitude, lng: @item.longitude }]
    end

  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path, status: :see_other
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to item_path(@item)
  end

  def my_items
    @items = current_user.items

  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :price, :poster_url, :univers)
  end
end

app/controllers/pages_controller.rb
require 'geocoder'

class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="font-b">
  <div class="fort-title">
    <h1>Vos réservations</h1>
  </div>


<div class="container">
  <div class="cards">
    <% @bookings.each do |booking| %>
      <div class="card-category">
        <%= image_tag booking.item.poster_url, class:"card-image", alt: "" %>
        <div class="card-category-info">
          <h2><%= booking.item.name %></h2>
           <p><%= booking.start_at.strftime('%-d %b. %y') %> au <%= booking.end_at.strftime('%-d %b. %y') %></p>
            <p><%= booking.status %></p>

          <%# <% if item.user.present? %>
            <%# <%= image_tag item.user.photo_url, class: "card-category-user" %>
          <%# <% else %>
          <%# <p>Aucune photo d'utilisateur disponible</p> %>
          <%# <% end %>

             <img src="<%= booking.item.user.photo_url %>" class="avatar">

        </div>
      </div>
    <% end %>
  </div>
</div>
</div>





</div>

app/views/items/edit.html.erb
<div class="fond3" >
  <div class="box4">
    <div class="cards_form_add">
        <h2>Edit an item </h2>

          <%= simple_form_for @item, html: { multipart: true } do |f| %>
        <%= f.input :name, placeholder: 'Name', required: true %>
        <%= f.input :price, placeholder: 'Price', required: true %>
        <%= f.input :description, placeholder: 'Description', required: true %>
         <%= f.select :univers, Item::UNIVERS %>
        <%= f.input :poster_url, as: :url, label: 'Upload a photo', required: true %>
        <%= f.submit 'Modify Item', class: 'button_add_item' %>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<div class="main-image">
  <div class= "title-index">
    <h1>Liste d'objets</h1>
  </div>
  <div class="container">
    <div class="cards">
      <% @items.each do |item| %>
        <div class="card-category">
          <%= image_tag item.poster_url, class:"card-image", alt: "" %>
          <div class="card-category-info">
            <h2><%= item.name %></h2>
            <p><%=item.price %>€</p>
            <%= link_to "infos", item_path(item), class: "button-info" %>

            <%# <% if item.user.present? %>
              <%# <%= image_tag item.user.photo_url, class: "card-category-user" %>
            <%# <% else %>
            <%# <p>Aucune photo d'utilisateur disponible</p> %>
            <%# <% end %>

            <img src="<%=item.user.photo_url %>" class="avatar">

          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/items/my_items.html.erb
<div class="font-b">
  <div class="fort-title">
    <h1>Vos objets mythiques</h1>
  </div>
  <div class="container">
    <div class="cards">
      <% @items.each do |item| %>
        <div class="card-category">
          <%= link_to item_path(item), class: "navbar-brand" do %>
            <%= image_tag item.poster_url, class:"card-image", alt: "" %>
              <% end %>
              <div class="card-category-info">
                <h2><%= item.name %></h2>
                <img src="<%= item.user.photo_url %>" class="avatar">
              </div>
            </div>
          <% end %>
    </div>
  </div>
</div>

          <%# <% if item.user.present? %>
            <%# <%= image_tag item.user.photo_url, class: "card-category-user" %>
          <%# <% else %>
          <%# <p>Aucune photo d'utilisateur disponible</p> %>
          <%# <% end %>

app/views/items/new.html.erb
<div class="fond3" >
  <div class="box4">
    <div class="cards_form_add">
        <h2>Add an item</h2>

          <%= simple_form_for @item, html: { multipart: true } do |f| %>
        <%= f.input :name, placeholder: 'Name', required: true %>
        <%= f.input :price, placeholder: 'Price', required: true %>
        <%= f.input :description, placeholder: 'Description', required: true %>
         <%= f.select :univers, Item::UNIVERS %>
        <%= f.input :poster_url, as: :url, label: 'Upload a photo', required: true %>
        <%= f.submit 'Create Item', class: 'button_add_item' %>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<div class="font-b">
<div class="vide">
</div>
  <div class="block1">
    <div class="item-poster-wrapper">
      <div class="item-poster">
        <img src="<%= @item.poster_url %>" alt="#">
      </div>

                <div class= "edit">
                <br>
  <% if @item.user == current_user %>
    <%= link_to "Modifier", edit_item_path(@item), class: "button-home1" %>
    <%= link_to "Supprimer", item_path(@item), data: {turbo_method: :delete, turbo_confirm: "Etes vous sur ?"}, class: "button-home2" %>
  <% end %>
      </div>
    </div>

      <div class="info-section">
        <div class="item-name">
          <h1><%= @item.name %></h1>
        </div>

        <div class="item-description">

          <p> <%= @item.description %></p>
        </div>
            <div class="item-price">
              <h2>  <%= @item.price %> € /jours </h2>
            </div>


      </div>


    </div>


  <% if @item.user != current_user %>
    <div class="block2">
      <div class="map-section",
          data-controller="map"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">

      </div>

      <div class="booking-form">
      <h2 class= "text-center" >Reservez cet objet ! </h2>
      <%= simple_form_for [@item, @booking] do |f| %>
        <div style="margin-right: -8px;">
          <div style="margin-left: 200px">
                <div class="booking-date">
          <%= f.input :start_at, as: :string,  placeholder: "Dates", label: false, input_html: {data: { controller: "flatpickr" }, style: "width: 30vh; height: 4em;display:none"} %>
          </div>
                </div>
        <div class="booking-reserve">
        <%= f.submit "Réserver !", class:"button-home"%>
        </div>

        </div>
      <% end %>
      </div>
    </div>

  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MEETICAllGears</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>

  <body>
  <%= render "shared/navbar" %>
  <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="content">
  <div class ='box'>
    <div class= 'infos'>
     <h1>Meetic All Gears</h1>
      <div class="taille-p">
        <p> Trouver les meilleurs objets mythiques de la pop culture, pour vos projets de tous les jours !</p>
      </div>
      <div class="buttons">
    <%= link_to "Voir les objets mythiques", items_path, class:"button-home" %>
    <% if current_user.nil? %>
      <%= link_to "S'inscrire", new_user_registration_path, class: "btn-login" %>
      <%= link_to "Déjà inscrit?", new_user_session_path, class: "button_already" %>
    <% end %>
    <p><span data-controller="typed-js"></span></p>
</div>
  </div>
</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="fixed-top">
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <div class="container-fluid">

      <%= link_to items_path, class: "navbar-brand" do %>
        <%= image_tag "https://farm3.static.flickr.com/2131/2264940881_0b3aea4854.jpg" %>
      <% end %>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <% if user_signed_in? %>
          <%# ajouter le logo en dessous pour linker à la page home %>
            <%# <li class="nav-item active">
              <%= link_to "Home", "#", class: "nav-link" %>
            <%# </li> %>
            <%# linker la bonne page (ajout d'un item) sur le bouton ajouter une arme %>




            <li class="nav-item dropdown">
              <%= image_tag current_user.photo_url, class: "avatar-nav dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Mes réservations", bookings_path, class: "dropdown-item" %>
                <%= link_to "Mes objets", my_items_path, class: "dropdown-item" %>
                <%= link_to "Ajouter un objet", new_item_path, class: "dropdown-item" %>
                <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "dropdown-item", data: {turbo_method: :delete} %>
              </div>
            </li>
          <% else %>
                <%= image_tag "https://static.vecteezy.com/system/resources/previews/000/512/576/original/vector-profile-glyph-black-icon.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>

            <!--li class="nav-item"-->
              <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
            <!--/li-->
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>